# Generated by Django 3.1 on 2021-11-08 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='expiry_date',
        ),
    ]
